#version: '3.8'

services:
  traefik:
    image: traefik:v2.11.6
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    command:
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.mysql.address=:3306"
      - "--entrypoints.traefikapi.address=:8080"
      - "--entrypoints.nuxt.address=:3000"
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=DEBUG"
    ports:
      # Web
      - "80:80/tcp"
      - "443:443/tcp"
      - "3000:3000"
      # MariaDB
      - "3306:3306/tcp"
      # Dashboard Traefik
      - "8080:8080"
    labels:
      - "traefik.enable=true"

      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web
    deploy:
      resources:
        limits:
          memory: 300m

  nuxt:
    build: 
      context: ./front
      args:
        NUXT_ENV: ${NUXT_ENV}
        NUXT_JWT_SECRET: ${NUXT_JWT_SECRET}
        SYLIUS_HOST: ${SYLIUS_HOST}
    container_name: ${NUXT_CONTAINER_NAME}
    privileged: true
    environment:
      NUXT_ENV: ${NUXT_ENV}
      NUXT_JWT_SECRET: ${NUXT_JWT_SECRET}
      SYLIUS_HOST: ${SYLIUS_HOST}
      SYLIUS_BASE_URL: http://${SYLIUS_CONTAINER_NAME}:80
    volumes:
      - "nuxt:/app"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt.rule=Host(`${NUXT_HOST}`)"
      - "traefik.http.routers.nuxt.entrypoints=web"
      - "traefik.http.routers.nuxt.tls=false"
      - "traefik.http.routers.nuxt.service=nuxt"
      - "traefik.http.services.nuxt.loadbalancer.server.port=3000"
      

  sylius:
    build: ./backend
    container_name: ${SYLIUS_CONTAINER_NAME}
    privileged: true
    hostname: ${SYLIUS_CONTAINER_NAME}
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}/${MYSQL_DATABASE}?serverVersion=8&charset=utf8mb4
      SYLIUS_HOST: ${SYLIUS_HOST}
      MAILER_DSN: ${MAILER_DSN}
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
      SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN: ${SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN}
      SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN: ${SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN}
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN: ${SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN}
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN: ${SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN}
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE}
      APACHE_LOG_DIR: /varr/www/logs
      XDEBUG_MODE: ${XDEBUG_MODE}
      #importan pour autoriser les requette sur l'api de sylius depuis nuxt
      SYLIUS_REGEX_REQUEST_ACCEPTED: ${SYLIUS_REGEX_REQUEST_ACCEPTED}
      XDEBUG_CONFIG: >-
                client_host=host.docker.internal
                client_port=${XDBUG_PORT}
                log=/dev/stdout
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=${PHP_IDE_CONFIG_NAME}
    volumes:
      - sylius:/app:rw,cached

      # if you develop on Linux, you may use a bind-mounted host directory instead
#     - ./var:/srv/sylius/var:rw
      - sylius-public:/app/public:rw,delegated
      
      # if you develop on Linux, you may use a bind-mounted host directory instead
#     - ./public/media:/srv/sylius/public/media:rw
      - sylius-public-media:/app/public/media:rw
    networks:
      web:
        aliases:
          - ${SYLIUS_HOST}  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sylius.rule=Host(`${SYLIUS_HOST}`)"
      - "traefik.http.services.sylius.loadbalancer.server.port=80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.localhost`)"
      - "traefik.http.routers.mailhog.service=mailhog"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"

  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      web:
        aliases:
          - ${MYSQL_HOST}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

volumes:
  db_data:
  sylius:
  sylius-public:
  sylius-public-media:
  nuxt:

networks:
  web:
    external: true
