# Définir des arguments de build
ARG NUXT_JWT_SECRET=secret-key
ARG SYLIUS_HOST=sylius.localhost
ARG NUXT_ENV=prod

FROM node:22 as builder

ENV NUXT_JWT_SECRET=${NUXT_JWT_SECRET}
ENV SYLIUS_HOST=${SYLIUS_HOST}

WORKDIR /app

# Copier uniquement les fichiers nécessaires
COPY package*.json ./

# Installer les dépendances de build
RUN npm install

# Copier le reste des fichiers
COPY . .

# Construire le projet
RUN npm run build

# Étape finale
FROM node:22

ENV NUXT_JWT_SECRET=${NUXT_JWT_SECRET}
ENV SYLIUS_HOST=${SYLIUS_HOST}

WORKDIR /app

# Copier les fichiers nécessaires depuis l'étape précédente
COPY --from=builder /app .

ENV HOST 0.0.0.0
EXPOSE \
  3000 

# Ajouter le script d'entrée
RUN mv entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# garder le conteneur ouvert
CMD ["/entrypoint.sh"]

