# Étape 1 : Utiliser une image officielle de PHP avec Apache comme base
FROM php:8.3-apache

# Étape 2 : Installer Node.js et les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    git \
    curl \
    nano \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Étape 3 : Installer les dépendances de l'application Nuxt.js
WORKDIR /var/www/html

# Étape 5 : Configurer Apache pour agir comme proxy pour Node.js
RUN a2enmod proxy proxy_http rewrite

#COPY ./apache-vhost.conf /etc/apache2/sites-available/000-default.conf

# Étape 6 : Exposer le port utilisé par Apache
EXPOSE 80

# Ajouter le script d'entrée
COPY ./entrypoint.sh /usr/local/bin/entrypoint.sh

# Définir les permissions pour Apache
RUN chmod +x /usr/local/bin/entrypoint.sh 

# Commande par défaut
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
